"""Models for Outfit-of-the-Day: a daily, weather-aware outfit pick generated by re-running
the existing Styling Pipeline with a synthesized request_text — no new recommendation logic,
just a scheduled/cached wrapper around it (see app/styling/ootd.py). The styling context isn't
a hand-picked "persona" — it's derived automatically from the member's real history and
wardrobe (app/styling/member_context.py); `extra_hint` below is just an optional freeform
addition on top of that, not a replacement for it."""

from datetime import date as date_type
from typing import Any, Dict, Optional
from sqlalchemy import Boolean, Date, DateTime, ForeignKey, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.models.base import Base, generate_uuid, utc_now


class OOTDSubscription(Base):
    """One row per (tenant, member): opt-in settings for automatic daily outfit-of-the-day
    generation (app/worker/ootd_scheduler.py's daily loop reads enabled=True rows). Absence of
    a row, or enabled=False, just means that member is skipped by the automatic daily run — the
    on-demand GET/POST endpoints work regardless, with location passed explicitly."""

    __tablename__ = "ootd_subscriptions"
    __table_args__ = (UniqueConstraint("tenant_id", "member_id", name="uq_ootd_subscription_member"),)

    id: Mapped[str] = mapped_column(String(64), primary_key=True, default=lambda: generate_uuid("ootdsub"))
    tenant_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    member_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)

    location: Mapped[str] = mapped_column(String(128), nullable=False)
    extra_hint: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    updated_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True), default=utc_now, onupdate=utc_now, nullable=False,
    )


class OutfitOfTheDay(Base):
    """One row per (tenant, member, calendar date, location): the generated pick for that day.
    Wraps a real StylingRequest (produced by the normal /recommendations pipeline under the
    hood) rather than duplicating outfit-generation logic — this table exists purely so a
    repeated request for the same member/day/location returns the same cached result instead
    of re-running the full pipeline (and re-billing the vision/LLM calls) every time."""

    __tablename__ = "outfits_of_the_day"
    __table_args__ = (
        UniqueConstraint("tenant_id", "member_id", "for_date", "location", name="uq_ootd_member_date_location"),
    )

    id: Mapped[str] = mapped_column(String(64), primary_key=True, default=lambda: generate_uuid("ootd"))
    tenant_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    member_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)

    for_date: Mapped[date_type] = mapped_column(Date, nullable=False, index=True)
    location: Mapped[str] = mapped_column(String(128), nullable=False)
    # The full auto-derived context paragraph (plus any extra_hint) actually used to generate
    # this pick — kept for transparency/debugging, not a short label, hence Text not String(64).
    context_used: Mapped[str] = mapped_column(Text, nullable=False)
    weather_snapshot: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict, nullable=False)

    styling_request_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("styling_requests.id", ondelete="CASCADE"), nullable=False,
    )
    generation_source: Mapped[str] = mapped_column(
        String(16), nullable=False, default="on_demand",  # "on_demand" | "scheduled"
    )

    created_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), default=utc_now, nullable=False)
