name: TEMP Reset Postgres Password

on:
  workflow_dispatch: {}

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Reset postgres user password via trusted local socket
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            docker exec pipeline_postgres psql -U postgres -c "ALTER ROLE postgres WITH PASSWORD 'TFvyGjgzUcJ09GGg2X-bTzlV6yGuUrnD';"
